name: First Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  commit_comment:
    types: [created]
  Workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: test
        run: 
          echo "This is my first workflow"
          printenv
      
  